---
version: "3.8"
services:
  movies:
    image: srk421/paytmmovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  train:
    image: srk421/paytmtrains:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  dth:
    image: srk421/paytmdth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  recharge:
    image: srk421/paytmrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
